chore: prise en compte du code d'hamadoun et ajout des tests sur le n…
RISE-UP-TECH/adjProjectWeb pull request #17
Opened 2023-09-04 18:59 UTC by paul1230

PR rejection ok

2023-09-04 20:02 UTC, dfatoumata requested changes

2023-09-04 20:02 UTC, dfatoumata commented on src/pages/Crm/AdjustmentsUploader/index.test.tsx
> -      );
Là il faut mettre à jour le tester non le supprimer

2023-09-04 20:02 UTC, dfatoumata commented on src/pages/Crm/AdjustmentsUploader/index.test.tsx
> -      );
Là il faut mettre à jour le tester non le supprimer

2023-09-04 20:02 UTC, dfatoumata commented on src/pages/Crm/AdjustmentsUploader/index.tsx
> +    } catch (e: any) {
Pas de type any

2023-09-04 21:48 UTC, paul1230 commented on src/pages/Crm/AdjustmentsUploader/index.tsx
> +    } catch (e: any) {
Pour le type any, j'ai essayer de mettre un typage, mais à chaque fois j'ai ce message "Catch clause variable type annotation must be 'any' or 'unknown' if specified. "

2023-09-04 21:48 UTC, paul1230 commented on src/pages/Crm/AdjustmentsUploader/index.test.tsx
> -      );
Hello ! au fait ici c'est une ancienne code de Mamady, lors qui cliquait sur le bouton d'upload il affichait ce Json stringify.

C'est pour ça que l'id est à 0 s'était juste pour des testes factuels.

2023-09-13 14:25 UTC, dfatoumata approved these changes
Well done 👍

2023-09-13 14:25 UTC, merged